//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomska1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poglavje
    {
        public int ID_Poglavja { get; set; }
        public string Naslov { get; set; }
        public int Letnik_FK { get; set; }
        public int Predmet_FK { get; set; }
    
        public virtual Letnik Letnik { get; set; }
        public virtual Predmeti Predmeti { get; set; }
    }
}
