//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomska1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stopnja_Težavnosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stopnja_Težavnosti()
        {
            this.Kontrolne_Naloge = new HashSet<Kontrolne_Naloge>();
        }
    
        public int ID_Težavnosti { get; set; }
        public string Ime_Težavnosti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrolne_Naloge> Kontrolne_Naloge { get; set; }
    }
}
